#!/bin/env bash
#
source variables

function get_token_response {
  response=$(curl -sX POST "https://identity.api.rackspacecloud.com/v2.0/tokens" -H "Content-Type: application/json" \
      -d "{\"auth\":{\"RAX-KSKEY:apiKeyCredentials\":{\"username\":\"${USERNAME}\", \"apiKey\":\"${APIKEY}\"}}}")
}

function get_token_from_response {
  echo ${response} | python -m json.tool | grep token -A5 | grep id | awk -F":" '{print $2}' | tr -d " " | tr -d "\"" | tr -d ","
}

get_token_response
get_token_from_response
