#!/bin/bash
TOKEN=
region=
ddi=
lb_id=
curl -vsk -X POST -H "Content-Type: application/json" -H "X-Auth-Token: ${TOKEN}" "https://${region}.loadbalancers.api.rackspacecloud.com/v1.0/${ddi}/loadbalancers/${lb_id}/accesslist" -d @- <<EOF
{
    "accessList": [
        {
            "type": "ALLOW",
            "address": "127.0.0.1"
        }
    ]
}
EOF
